#!/usr/bin/env python3
"""Отправить текст на GitHub (комментарий, правку комментария, описание PR) через гейт кодировки.

Боты пишут в тикеты по-русски, и не раз комментарий доходил до GitHub строкой знаков «?»:
текст по дороге проходил через однобайтовую кодовую страницу (консоль Windows, аргумент
командной строки, неверно настроенный shell), и каждая буква, которой там нет, становилась «?».
Прочитать такой комментарий нельзя, а исходный текст уже потерян. Скрипт закрывает обе дыры:

1. гейт: файл читается как строгий UTF-8, и текст отклоняется (код 2, ничего не отправлено),
   если в нём есть U+FFFD, буквальные `\\n` вместо переводов строк или похожие на кашу знаки
   вопроса («???», «?? ???? ???», заметная доля «?» среди букв) — вне блоков кода;
2. сверка: тело уходит файлом (`gh api -F body=@файл`, без командной строки), после отправки
   комментарий читается с GitHub и сравнивается с файлом; не совпало — комментарий
   переписывается из файла ещё раз, а если и это не помогло, удаляется, и скрипт выходит с кодом 1.

    python3 gh_post.py check <файл>
    python3 gh_post.py comment <owner/repo> <номер тикета или PR> <файл>
    python3 gh_post.py edit <owner/repo> <id комментария> <файл>
    python3 gh_post.py pr-body <owner/repo> <номер PR> <файл>
    python3 gh_post.py pr <owner/repo> <head> <base> <файл>   # первая строка — заголовок, дальше тело
    python3 gh_post.py scan <owner/repo> [--days 3]           # найти уже испорченные комментарии

`scan` перечисляет комментарии последних дней, которые гейт отклонил бы. То же самое каждые
10 минут делает janitor и пишет найденное в `projects/<проект>/MOJIBAKE.md`; испорченный
комментарий восстанавливает любой бот правкой `edit` того же комментария (по смыслу ASCII-остова,
соседних сообщений и учёта), и после этого он из файла пропадает сам.
"""
import json
import re
import subprocess
import sys
import tempfile
from datetime import datetime, timedelta, timezone

CODE_BLOCK = re.compile(r"```.*?(```|$)", re.S)
INLINE_CODE = re.compile(r"`[^`\n]*`")
# Три «?» подряд не пишет никто, а каша из подряд идущих «слов» из одних «?» — это
# буквы, которые потерялись по дороге.
QUESTION_RUN = re.compile(r"\?{3,}")
QUESTION_WORDS = re.compile(r"(?:\?{2,}[\s.,:;!()\-]+){2,}\?+")
GATE_MESSAGE = ("Текст для GitHub пишется файлом в UTF-8 с настоящими переводами строк и уходит "
                "только через gh_post.py (LUNOBOT.md § 2).")


def prose(text):
    """Текст без блоков и вставок кода: в коде «???» и `\\n` — законное содержимое."""
    return INLINE_CODE.sub(" ", CODE_BLOCK.sub(" ", text))


def check_text(text):
    """Причина отказа или пустая строка, если текст можно отправлять."""
    if not text.strip():
        return "текст пуст"
    if "�" in text:
        return "в тексте символ замены U+FFFD: кодировка испорчена ещё до отправки"
    body = prose(text)
    if "\\n" in body:
        return "в тексте буквальные \\n вместо переводов строк"
    if QUESTION_RUN.search(body) or QUESTION_WORDS.search(body):
        return "в тексте подряд идущие «?» на месте букв: кодировка испорчена"
    letters = sum(ch.isalpha() for ch in body)
    marks = body.count("?")
    if marks >= 5 and marks > 0.15 * (letters + marks):
        return "в тексте слишком много «?» относительно букв: похоже на испорченную кодировку"
    return ""


def read_text(path):
    with open(path, "rb") as f:
        raw = f.read()
    try:
        return raw.decode("utf-8")
    except UnicodeDecodeError as err:
        raise SystemExit(f"отклонено: файл {path} не в UTF-8 ({err}). {GATE_MESSAGE}")


def normalize(text):
    return "\n".join(line.rstrip() for line in text.replace("\r\n", "\n").split("\n")).strip()


def same_text(stored, sent):
    """Дошло ли до GitHub то, что отправлено.

    Прокси облачной среды дописывает в конец своё («Generated by Claude Code»), поэтому
    хвост после отправленного текста допустим — если он сам не испорчен. Испорченная
    кодировка меняет сам текст, и тогда начало не совпадёт.
    """
    stored, sent = normalize(stored), normalize(sent)
    if stored == sent:
        return True
    return stored.startswith(sent) and check_text(stored[len(sent):]) in ("", "текст пуст")


def gh(*args, check=True):
    out = subprocess.run(["gh", *args], capture_output=True, text=True, encoding="utf-8")
    if check and out.returncode != 0:
        raise SystemExit(f"gh {' '.join(args[:3])}: {out.stderr.strip()[:400]}")
    return out


def api(path, *args, check=True):
    out = gh("api", path, *args, check=check)
    if out.returncode != 0 or not out.stdout.strip():
        return None
    return json.loads(out.stdout)


def gate(path):
    text = read_text(path)
    reason = check_text(text)
    if reason:
        print(f"отклонено: {reason}. {GATE_MESSAGE}", file=sys.stderr)
        raise SystemExit(2)
    return text


def verify_comment(repo, comment, text, path):
    """Сравнить отправленное с файлом; при расхождении переписать, затем удалить."""
    cid = comment["id"]
    for attempt in range(2):
        got = api(f"repos/{repo}/issues/comments/{cid}")
        if got and same_text(got.get("body") or "", text):
            print(got.get("html_url", ""))
            return 0
        if attempt == 0:
            api(f"repos/{repo}/issues/comments/{cid}", "-X", "PATCH", "-F", f"body=@{path}", check=False)
    gh("api", "-X", "DELETE", f"repos/{repo}/issues/comments/{cid}", check=False)
    print(f"ошибка: GitHub хранит не тот текст, что в {path}; комментарий {cid} удалён. "
          "Проверь кодировку среды (UTF-8) и отправь заново.", file=sys.stderr)
    return 1


def verify_pr(repo, number, text, path):
    for attempt in range(2):
        got = api(f"repos/{repo}/pulls/{number}")
        if got and same_text(got.get("body") or "", text):
            print(got.get("html_url", ""))
            return 0
        if attempt == 0:
            api(f"repos/{repo}/pulls/{number}", "-X", "PATCH", "-F", f"body=@{path}", check=False)
    print(f"ошибка: описание PR {repo}#{number} не совпало с {path}; поправь его вручную "
          "из файла в UTF-8-среде.", file=sys.stderr)
    return 1


def post_comment(repo, number, path):
    text = gate(path)
    comment = api(f"repos/{repo}/issues/{number}/comments", "-F", f"body=@{path}")
    if not comment:
        raise SystemExit("комментарий не создан")
    return verify_comment(repo, comment, text, path)


def edit_comment(repo, cid, path):
    text = gate(path)
    comment = api(f"repos/{repo}/issues/comments/{cid}", "-X", "PATCH", "-F", f"body=@{path}")
    if not comment:
        raise SystemExit("комментарий не изменён")
    return verify_comment(repo, comment, text, path)


def pr_body(repo, number, path):
    text = gate(path)
    api(f"repos/{repo}/pulls/{number}", "-X", "PATCH", "-F", f"body=@{path}")
    return verify_pr(repo, number, text, path)


def create_pr(repo, head, base, path):
    text = gate(path)
    title, _, body = text.partition("\n")
    title = title.strip()
    if not title:
        raise SystemExit("первая строка файла — заголовок PR — пуста")
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", suffix=".md", delete=False) as f:
        f.write(body.lstrip("\n"))
        body_path = f.name
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", suffix=".txt", delete=False) as f:
        f.write(title)
        title_path = f.name
    pr = api(f"repos/{repo}/pulls", "-F", f"title=@{title_path}", "-f", f"head={head}",
             "-f", f"base={base}", "-F", f"body=@{body_path}")
    if not pr:
        raise SystemExit("PR не создан")
    if normalize(pr.get("title", "")) != normalize(title):
        print(f"ошибка: заголовок PR {pr.get('html_url')} не совпал с файлом", file=sys.stderr)
        return 1
    return verify_pr(repo, pr["number"], body.lstrip("\n"), body_path)


def scan(repo, days):
    since = (datetime.now(timezone.utc) - timedelta(days=days)).strftime("%Y-%m-%dT%H:%M:%SZ")
    found = 0
    page = 1
    while True:
        batch = api(f"repos/{repo}/issues/comments?since={since}&per_page=100&page={page}") or []
        for c in batch:
            reason = check_text(c.get("body") or "")
            if reason and reason != "текст пуст":
                found += 1
                print(f"{c['html_url']} ({c['user']['login']}, {c['created_at']}): {reason}")
        if len(batch) < 100:
            break
        page += 1
    if not found:
        print(f"{repo}: испорченных комментариев за {days} дн. нет")
    return 1 if found else 0


def main(argv):
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="backslashreplace")
        except (AttributeError, ValueError):
            pass
    if not argv:
        print(__doc__)
        return 2
    cmd, args = argv[0], argv[1:]
    if cmd == "check" and len(args) == 1:
        gate(args[0])
        print("годится")
        return 0
    if cmd == "comment" and len(args) == 3:
        return post_comment(*args)
    if cmd == "edit" and len(args) == 3:
        return edit_comment(*args)
    if cmd == "pr-body" and len(args) == 3:
        return pr_body(*args)
    if cmd == "pr" and len(args) == 4:
        return create_pr(*args)
    if cmd == "scan" and args:
        days = 3
        if "--days" in args:
            days = int(args[args.index("--days") + 1])
        return scan(args[0], days)
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
