"""Проверки гейта кодировки gh_post.py и шага janitor, который ищет испорченные комментарии."""

import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest.mock import patch

import gh_post
import janitor

# Настоящие комментарии, дошедшие до f4#1774 и f4#1778 07-10-2026 (начала).
BROKEN = [
    "???????? native Wayland ?????????.\n\n? ???????????? `github.com/unxed/wayland` (????? `vtui v0.1.396`):",
    "CI ?? ??????? `263a1bce22caaeeac5388399e2d21a923cfdd02f` ??????? ?? ??-?? ??????????????",
    "?? ?? ?? ?? ok",
]
GOOD = [
    "Проверено: текущий f4 main уже использует `github.com/unxed/vtui` v0.1.396.",
    "Почему?? Это же работало. А так? Или так?",
    "Регэксп `a???b` и вывод:\n\n```\n???? \\n ????\n```\n\nвсё в коде, это законно.",
    "Is this the right fix? Please check.",
]


class CheckTextTest(unittest.TestCase):
    def test_real_mojibake_is_rejected(self):
        for text in BROKEN:
            with self.subTest(text=text[:30]):
                self.assertTrue(gh_post.check_text(text))

    def test_normal_text_passes(self):
        for text in GOOD:
            with self.subTest(text=text[:30]):
                self.assertEqual(gh_post.check_text(text), "")

    def test_replacement_char_and_literal_newlines_are_rejected(self):
        self.assertIn("U+FFFD", gh_post.check_text("Текст � сломан"))
        self.assertIn("\\n", gh_post.check_text("Первая строка\\nвторая строка"))

    def test_share_of_question_marks(self):
        self.assertTrue(gh_post.check_text("a? b? c? d? e? f?"))

    def test_file_not_in_utf8_is_rejected(self):
        with TemporaryDirectory() as directory:
            path = Path(directory) / "body.md"
            path.write_bytes("Привет".encode("cp1251"))
            with self.assertRaises(SystemExit):
                gh_post.gate(str(path))
            path.write_text("Привет, всё в порядке.", encoding="utf-8")
            self.assertEqual(gh_post.gate(str(path)), "Привет, всё в порядке.")


class VerifyTest(unittest.TestCase):
    def test_comment_that_arrived_broken_is_rewritten_then_deleted(self):
        calls = []

        def fake_api(path, *args, check=True):
            calls.append((path, args))
            return {"body": BROKEN[0], "html_url": "u"}

        with patch.object(gh_post, "api", fake_api), patch.object(gh_post, "gh") as gh:
            self.assertEqual(gh_post.verify_comment("o/r", {"id": 7}, "Нормальный текст", "f"), 1)
        self.assertTrue(any("PATCH" in args for _, args in calls))
        gh.assert_called_once_with("api", "-X", "DELETE", "repos/o/r/issues/comments/7", check=False)

    def test_matching_comment_is_kept(self):
        with patch.object(gh_post, "api", return_value={"body": "Текст\r\n", "html_url": "u"}):
            self.assertEqual(gh_post.verify_comment("o/r", {"id": 7}, "Текст\n", "f"), 0)


class SameTextTest(unittest.TestCase):
    def test_footer_appended_by_proxy_is_accepted(self):
        stored = "Текст\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"
        self.assertTrue(gh_post.same_text(stored, "Текст\n"))

    def test_broken_text_is_not_the_same(self):
        self.assertFalse(gh_post.same_text("?????", "Текст"))
        self.assertFalse(gh_post.same_text("Текст\n\n?????? ????", "Текст"))


class JanitorMojibakeTest(unittest.TestCase):
    def test_file_lists_broken_comments_and_disappears_when_fixed(self):
        comment = {"id": 1, "html_url": "https://x/1", "created_at": "t",
                   "user": {"login": "unxed", "type": "User"}, "body": BROKEN[1]}
        bot = dict(comment, id=2, user={"login": "codecov[bot]", "type": "Bot"})
        with TemporaryDirectory() as directory:
            d = Path(directory)
            with patch.object(janitor, "gh_all", return_value=[comment, bot]):
                janitor.mojibake(d, "o/r")
            text = (d / "MOJIBAKE.md").read_text(encoding="utf-8")
            self.assertIn("id 1", text)
            self.assertNotIn("id 2", text)
            with patch.object(janitor, "gh_all", return_value=[dict(comment, body="Исправлено.")]):
                janitor.mojibake(d, "o/r")
            self.assertFalse((d / "MOJIBAKE.md").exists())


if __name__ == "__main__":
    unittest.main()
